regression: exit 1 if tests fail; \e -> \033 for osx/travis-ci

diff --git a/bin/run-tests b/bin/run-tests
--- a/bin/run-tests
+++ b/bin/run-tests
@@ -9,11 +9,11 @@ ensure_verifies()
   # Function. Parameter 1 is the return code
   # Para. 2 is the name of the benchmark.
   if [ "${1}" -ne "0" ]; then
-    echo -e "\r\e[31mFailed benchmark ${2}.\e[0m    "
-    echo -ne "\e[31mERROR: expected benchmark to verify.\e[0m"
+    echo -e "\r\033[31mFailed benchmark ${2}.\033[0m    "
+    echo -ne "\033[31mERROR: expected benchmark to verify.\033[0m"
     PASSED=0
   else
-    echo -ne "\r\e[32mPassed benchmark ${2}.\e[0m    "
+    echo -ne "\r\033[32mPassed benchmark ${2}.\033[0m    "
   fi
 }
 
@@ -22,13 +22,13 @@ ensure_fails()
   # Function. Parameter 1 is the return code
   # Para. 2 is the name of the benchmark.
   if [ "${1}" -ne "1" ]; then
-    echo -e "\r\e[31mFailed benchmark ${2}.\e[0m    "
-    echo -e "\e[31m*** SOUNDNESS ERROR ***************************************"
+    echo -e "\r\033[31mFailed benchmark ${2}.\033[0m    "
+    echo -e "\033[31m*** SOUNDNESS ERROR ***************************************"
     echo "*** SOUNDNESS ERROR: Expected benchmark to fail."
-    echo -e "*** SOUNDNESS ERROR ***************************************\e[0m"
+    echo -e "*** SOUNDNESS ERROR ***************************************\033[0m"
     PASSED=0
   else
-    echo -ne "\r\e[32mPassed benchmark ${2}.\e[0m    "
+    echo -ne "\r\033[32mPassed benchmark ${2}.\033[0m    "
   fi
 }
 
@@ -68,4 +68,5 @@ if [ $PASSED == 1 ]; then
     echo "All tests passed."
 else
     echo "There were failing test cases."
+    exit 1
 fi
